### ISSUE TITLE
[Feature] Pull mode or remote backup

### ISSUE THREAD

**Issue by micheelengronne** [gardener/etcd-backup-restore#207]
**Feature (What you would like to be added):**
Pull backup from a remote etcd to a local storage instead of pushing a local etcd backup to a remote storage.

**Motivation (Why is this needed?):**
To do backups in that way increases the security as the etcd cluster that is backed up has no access to the backups themselves. It is a safeguard against compromised etcd clusters (one of the usecases of a backup). It can help to prevent the [VFEmail crisis](https://www.theregister.co.uk/2019/02/12/vfemail_hacked_wiped/)

I created a similar issue for [stash](https://github.com/stashed/stash/issues/979)

**Comment by swapnilgm** [comment]
Hi @micheelengronne,

From whatever i understood from the provided description, this feature is already supported. Following is my explanation for the same.
Etcd-backup-restore does pull the backups from etcd cluster with configured endpoints and upload to configured object store. As per the helm chart, it just needs to reside along side etcd sharing the data directory only for restoration purpose. Otherwise its not mandatory for etcd-backup-restore to reside alongside etcd. Even when, it runs as sidecar in etcd statefulset, it is running in separate container. The backup credentials are accessible only to etcd-backup-restore, and hence backup access are restricted to etcd-backup-restore utility. Etcd cluster doesn't know anything about backups. So, even if it gets comprised it won't have access to backups.

Feel free to correct me i interpreted your request wrongly.
