### ISSUE TITLE
[Feature] Retry full backups to avoid false positives in alerts

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#258]
**Feature (What you would like to be added):**
If regular full snapshot backup fails, they are retried only in the next interval (typically, `24h`). We should retry the full snapshot backup in shorter time frame (say, `10m`, `15m` or `20m`).

**Motivation (Why is this needed?):**
Alerts are configured to fire if the latest full backups are more than `24h` old. These typically get resolved automatically in the next interval when the full backup goes through. So, most of the alerts are false positives that get resolved automatically. This makes it hard to automate the follow up process using ticketing systems (mandated by audit).

Retrying within a range of `10m-20m` might resolve the issue automatically earlier so that alerts fire only if retries also fail.

**Approach/Hint to the implement solution (optional):**

**Comment by amshuman-kr** [comment]
@shreyas-s-rao You mentioned that the problem with failed etcd backup alerts was frequently in shoot clusters that got hibernated before the full snapshot schedule. I indeed saw many shoots where this was happening. The solution to this might be either to adjust the full snapshot cron string based on the hibernation schedule or taking a full snapshot just before hibernation as in your PR https://github.com/gardener/etcd-druid/pull/59. I prefer the latter.

You also mentioned that full snapshot are retried. But I could not see this in the code. Did you mean that the backup-restore sidecar would restart if the full snapshot failed? -> https://github.com/gardener/etcd-backup-restore/blob/72720b4d2f117ba571b08d48c4ab37e0e68764ca/pkg/snapshot/snapshotter/snapshotter.go#L490-L493

**Comment by shreyas-s-rao** [comment]
@amshuman-kr All snapshots (full and delta) are uploaded via chunk upload. And there is an exponential backoff for chunk upload retries [here](https://github.com/gardener/etcd-backup-restore/blob/72720b4d2f117ba571b08d48c4ab37e0e68764ca/pkg/snapstore/utils.go#L134). So both full and delta snapshot failures are re-attempted.

Regarding the missed snapshots issue, we can either modify [this](https://github.com/gardener/etcd-backup-restore/blob/72720b4d2f117ba571b08d48c4ab37e0e68764ca/pkg/server/backuprestoreserver.go#L202) value to something like 23.5 instead of 24, so that we can accommodate the previous day's full snapshots that was probably a few minutes late. Or else, even the full snapshot on hibernation is a safe approach, and is implemented anyway.
I would suggest fixing the issue within backup sidecar itself, so that it can be consumed bug-free by anybody without druid too.

**Comment by amshuman-kr** [comment]
> All snapshots (full and delta) are uploaded via chunk upload. And there is an exponential backoff for chunk upload retries [here](https://github.com/gardener/etcd-backup-restore/blob/72720b4d2f117ba571b08d48c4ab37e0e68764ca/pkg/snapstore/utils.go#L134). So both full and delta snapshot failures are re-attempted.

Ok. This covers upload errors but not other errors during full snapshot (e.g. timeout while taking the snapshot). But I guess those are really rare.

**Comment by amshuman-kr** [comment]
> Regarding the missed snapshots issue, we can either modify this value to something like 23.5 instead of 24, so that we can accommodate the previous day's full snapshots that was probably a few minutes late. Or else, even the full snapshot on hibernation is a safe approach, and is implemented anyway.
I would suggest fixing the issue within backup sidecar itself, so that it can be consumed bug-free by anybody without druid too.

It sure makes sense to calculate [this value](https://github.com/gardener/etcd-backup-restore/blob/72720b4d2f117ba571b08d48c4ab37e0e68764ca/pkg/server/backuprestoreserver.go#L202) based on the full-snapshot schedule. But it still will be considered only when the sidecar restarts. I don't think the hibernation case can be addressed in the back-restore sidecar because it is not at all aware of anything called hibernation. It can only be addressed (as in https://github.com/gardener/etcd-druid/pull/59) in etcd-druid.
