### ISSUE TITLE
[BUG] Database verification should check WALs also for latest revision

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#260]
**Describe the bug:**
The database validation logic currently [only checks the bolt DB data](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/initializer/validator/datavalidator.go#L265-L301) for the latest revision in the etcd directory.

It is possible that  etcd has terminates abnormally and fails to flush the changes from the WALs to the bolt DB but if the latest backup (full or delta) already have backed up some of the changes that are still in the WALs. If this happens, the data validation might see a revision in the etcd data directory (based only on the bold DB) that is older than the revision that has already been backed up. This will lead to an unnecessary data restoration (with possible data loss if not all the WALs where backed up).

**Expected behavior:**
The WALs should also be checked while calculating the latest revision in the etcd directory so that the situation where the latest revision in the backup is more recent than the revision that the validation logic sees in the etcd data directory.

**How To Reproduce (as minimally and precisely as possible):**
Hard to reproduce.

**Logs:**
Logs in the backup-restore sidecar like below.
```
current etcd revision (2314180238) is less than latest snapshot revision (2314180239): possible data loss
```
**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by ishan16696** [comment]
I tried to read the WAL file with ReadAll() method but unable to find any dataStructure or anything that can give latest revision from WAL file or changes which are not committed to DB file.
Actually WALs file is not meant to give us revision(or changes which are not committed to DB file) because WALs file was introduced just for **RAFT** protocol.

One possible solution can be if current etcd Revision less than latest snapshot revision then start the embedded etcd on same data dir and then apply the watch api from that etcd Revision , so that we can apply the events on etcd which are ahead and not present in db file. 
And one more observation is that DB file and WALs file can sync automatically because DB file is not corrupted that's why we are getting etcd revision , so we can start embedded etcd and wait for etcd DB file and WALs file to get in sync.

**Comment by amshuman-kr** [comment]
> I tried to read the WAL file with ReadAll() method but unable to find any dataStructure or anything that can give latest revision from WAL file or changes which are not committed to DB file.

I would advise against using `ReadAll()`. Especially, for the WAL files, we don't want to load them into memory. 

> Actually WALs file is not meant to give us revision(or changes which are not committed to DB file) because WALs file was introduced just for RAFT protocol.

Perhaps the [`go.etcd.io/etcd/v3/wal`](https://github.com/etcd-io/etcd/blob/master/wal/) can be used?

> And one more observation is that DB file and WALs file can sync automatically because DB file is not corrupted that's why we are getting etcd revision , so we can start embedded etcd and wait for etcd DB file and WALs file to get in sync.

This is an interesting idea. This was an option we had considered for the database verification itself. But we had found that the verification can be done much faster if we use some package in https://github.com/etcd-io/etcd or https://github.com/etcd-io/bbolt. I am not necessarily saying we shouldn't start an embedded etcd for this. Just saying that we have to keep latency in mind.
