### ISSUE TITLE
[Feature] Handling etcd transactions correctly during backup and restoration

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#283]
**Feature (What you would like to be added):**
1. Ensure that events from a single etcd transaction are not spread across multiple incrementation snapshots.
1. Group together events in an incremental snapshot into a single etcd transaction while restoring the etcd database from backup if the events belonged to a single etcd tranaction originally.
1. Avoid using etcd transactions for any other purpose while restoring etcd database from backup.

**Motivation (Why is this needed?):**
While restoring etcd database from backup, we currently group events from a single incremental snapshot into a [single etcd transaction](https://etcd.io/docs/v3.4.0/learning/api/#transaction). This can lead to two issues.
1. Inconsistency between revisions before and after restoration.
> Quote from https://etcd.io/docs/v3.4.0/learning/api/#transaction:
> this means the store’s revision is incremented only once for the transaction and all events generated by the transaction will have the same revision.
2. Failed restoration if an incremental snapshots has PUT or DELETE on the same key.
> Quote from https://etcd.io/docs/v3.4.0/learning/api/#transaction:
> However, modifications to the same key multiple times within a single transaction are forbidden.

**Approach/Hint to the implement solution (optional):**
1. Check if etcd watch response (used by the incremental snapshotter) always contains all the events from a single source transaction.
1. Check if etcd watch responses (used by the incremental snapshotter) always come in the ascending order of their `ModRevision`.
1. If the above two conditions hold good, use them to ensure that all events belonging to a transaction are captured in a single incremental snapshot and are not spread across multiple incremental snapshots.
1. Order events in an incremental snapshot based on their `ModRevision` and group events that have the same `ModRevision` into a single transaction during etcd database restoration.

**Comment by vlerenc** [comment]
Thanks @amshuman-kr . That looks like an important finding. If implemented, which seems necessary, it will possibly prolong our restoration times (a lot), right (transactions one-by-one)?

To clarify: This problem only appears "between" incremental snapshots. There we need it, because ETCD continues to run and is generating, based on the current revisions, more revisions that end up in follow-up incremental snapshots. The full snapshot will be restored "by file" and doesn't require transaction-based restoration, right? Then all following incremental snapshots (except the very last one, which is no useful optimisation) would be restored transaction by transaction?

When we are compacting incremental snapshots, what would that do in detail? It isn't about the ETCD "compaction", but we would rather bring up a local ETCD from the last full snapshot, apply the incremental snapshots and then switch out the previous with the new full snapshot/DB file. Is that right?

**Comment by abdasgupta** [comment]
Referring https://github.com/gardener/etcd-backup-restore/issues/263#issuecomment-726664952

**Comment by shreyas-s-rao** [comment]
@vlerenc This problem in applying delta events in transactions can occur anywhere in an incremental snapshot, based on the operation performed on the etcd when snapshotting. We have never encountered this issue in an etcd backing a k8s cluster, because of the way kube-apiserver interacts with etcd, which is only get, range, put, delete operations, and not full-fledged transactions. This is why the restoration mechanism as well as all our tests have worked for the past 2-3 years. Now we need to make sure our backup-restore solution works for any given etcd (not just backing a k8s cluster) and any possible etcd operations, which is why this fix becomes important. In that sense, yes, there's a good possibility that this would increase restoration duration. But with snapshot compaction coming in, we would see a drastic reduction in restoration time, and furthermore, controlled restorations (shoot unhibernation, seed migration, quorum loss scenarios for multi-node etcd ([refer](https://github.com/gardener/etcd-druid/pull/115/files#diff-7918fb156cb729ac55570b3318ff8e792f008e5fe087f0a7c7a36db71374411bR221)), where a final full snapshot will be taken before the previous etcd shutdown/scale-down) will depend only on the network bandwidth to download the full snapshot and start up the etcd, with no need to apply any incremental snapshots.

Regarding snapshot compaction mechanism itself, yes, that's precisely the steps that will be performed to compact the incremental snapshots, although this would be a background task and would not affect the backup sidecar's functioning or the etcd itself.

**Comment by abdasgupta** [comment]
So as per the ETCD3 API documentations (https://etcd.io/docs/v3.4.0/learning/api/)  Watch Streams are guaranteed to contain all the events of a transaction and the events are posted in ascending order by revision number :
```
Watch streams

Watches are long-running requests and use gRPC streams to stream event data. A watch stream is bi-directional; the client writes to the stream to establish watches and reads to receive watch events. A single watch stream can multiplex many distinct watches by tagging events with per-watch identifiers. This multiplexing helps reducing the memory footprint and connection overhead on the core etcd cluster.

Watches make three guarantees about events:

    Ordered - events are ordered by revision; an event will never appear on a watch if it precedes an event in time that has already been posted.
    Reliable - a sequence of events will never drop any subsequence of events; if there are events ordered in time as a < b < c, then if the watch receives events a and c, it is guaranteed to receive b.
    Atomic - a list of events is guaranteed to encompass complete revisions; updates in the same revision over multiple keys will not be split over several lists of events.
```

During restorations, events from same transaction are placed in a single commit :
https://github.com/gardener/etcd-backup-restore/blob/a48eac88fc15b298f9709c4767bdc839af7d23e2/pkg/snapshot/restorer/restorer.go#L648-L649

It takes care of validating the revisions, before and after applying the snapshots:
 https://github.com/gardener/etcd-backup-restore/blob/a48eac88fc15b298f9709c4767bdc839af7d23e2/pkg/snapshot/restorer/restorer.go#L669-L678 

As all the concerns are already  addressed, I am closing this issue for now. Feel free to reopen it if necessary.

**Comment by amshuman-kr** [comment]
Thanks for the investigation and clarification, @abdasgupta!
