### ISSUE TITLE
[BUG] Backup-restore is taking DeltaSnapshot even when --delta-snapshot-period is set to 0 seconds

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-backup-restore#324]
**Describe the bug:**
When `--delta-snapshot-period` is set to 0 seconds Etcd-backup-restore is taking DeltaSnapshot every time when sidecar container gets restart. 

**Expected behavior:**
Etcd-backup-restore should not take deltaSnapshot when `--delta-snapshot-period` is set to `0 seconds`.

**How To Reproduce (as minimally and precisely as possible):**
1. Run the `Etcd` and put some dummy data.
2. Now, run the Etcd-backup-restore with `--delta-snapshot-period=0s` and  Etcd-backup-restore will take `fullSnapshot`, now close the Etcd-backup-restore.
3.  Now put some more dummy data into Etcd.
4. Again starts the Etcd-backup-restore with `--delta-snapshot-period=0s` after this, now you can observe that `Etcd-backup-restore` end up taking `deltaSnapshot` which it Shouldn't have taken as `--delta-snapshot-period` is set to `0 sec`.

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by amshuman-kr** [comment]
I think this is expected behaviour as of now.

The `--delta-snapshot-period` applies to the repeated snapshots taken at regular intervals by the snapshotter. The snapshot (full or delta) taken at container startup is a safety mechanism which is independent of the regular intervals. 

If we want to disable snapshots (full or delta) completely (i.e. even during container start up), we should discuss what should be the contract (CLI flags etc.).

BTW I think there is a work-around to disable snapshots (full and delta) completely by setting the provider as blank.

**Comment by ishan16696** [comment]
Thanks @amshuman-kr, 
I wasn't aware that this is the intended behavior. 


> If we want to disable snapshots (full or delta) completely (i.e. even during container start up), we should discuss what should be the contract (CLI flags etc.).

Yeah we can discuss that.

**Comment by ishan16696** [comment]
As this is the intended behavior of `etcd-backup-restore` I am closing this issue for now.
But if there will be a need to introduce CLI flags to disable delta snapshots completely (even during container start up), we can create a separate issue for that.
