### ISSUE TITLE
Multi-Node ETCD Backup & Restore

### ISSUE THREAD

**Issue by vlerenc** [gardener/etcd-backup-restore#33]
In context of the Gardener ring, @rfranzke and @mandelsoft raise the question whether the current solution can be retrofitted for backup & restore in the multi-node Gardener ring.

**Comment by swapnilgm** [comment]
Yes. We can extend it. Although this breaks up the initial assumption of having single node cluster we had considered while designing it. So, there are some complications involved.

So, from gardener ring's perspective we will have three statefulSets running in three different clusters. Probably we will have to bring in logic of leader election there for backup so that only one backup sidecar can modify object store. Restoration would be the tricky part, we will have to carefully handle different cases like network partitioning, valid PV but not completely synced. But i think its feasible. 

Overall in my opinion it is extensible, but only condition is, to have all etcd names and url available before starting cluster. and tls certificate created/configured appropriately. Its quite a work, worth giving a shot, from gardener ring's perspective.

**Comment by vlerenc** [comment]
Thank you for the feedback!

**Comment by amshuman-kr** [comment]
Moved to https://github.com/gardener/etcd-druid/issues/107
