### ISSUE TITLE
Safe-guard against wrongly mounted volumes

### ISSUE THREAD

**Issue by abdasgupta** [gardener/etcd-backup-restore#466]
**Describe the bug:**
We found that there is a bug in csi-driver that can try to attempt to attach two disks to the same node at same time. And so, a race condition may happen and one node may be attached with a volume that is not intended for it. So, it's possible that volume used by ETCD of one shoot is mounted as volume used for ETCD of another shoot. We need to place a check in ETCD backup-restore, so that if this unfortunate mount happens, ETCD BR will not start at all

**Expected behavior:**
ETCD BR will not start ETCD and throw error if volume of any other shoot is mounted as ETCD volume.

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by vlerenc** [comment]
Thank you @abdasgupta, though I wouldn't call it a bug, but actually a safe-guard/protection, if that ever happens (the bug is with Kubernetes/CSI that leads to such cases of wrongly mounted volumes against which we want a safe-guard as the consequences would be dire).
/title Safe-guard against wrongly mounted volumes
/remove bug
/add enhancement

**Comment by ishan16696** [comment]
closing this issue as it is fixed in this PR https://github.com/gardener/etcd-backup-restore/pull/468 for master branch
/close.
