### ISSUE TITLE
[Enhancement] Lower file permissions of `.snap` files.

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/etcd-backup-restore#631]
**Enhancement (What you would like to be added):**
Files created by `etcd-backup-restore` at `/var/etcd/data/new.etcd/member/snap/` with extension `.snap` have file permissions `0644`.  As per the DISA STIGs requirements (e.g. [242445](https://www.stigviewer.com/stig/kubernetes/2021-04-14/finding/V-242445) and  [242459](https://www.stigviewer.com/stig/kubernetes/2021-04-14/finding/V-242459)) and taking into account the sensitive information in `etcd` backups the permissions of these files shall be lowered to `0600`.

**Motivation (Why is this needed?):**
To be compliant with DISA Kubernetes STIGs we require files managed by `etcd` to have `0600` permission or lower.

**Approach/Hint to the implement solution (optional):**

**Comment by shreyas-s-rao** [comment]
@AleksandarSavchev you mentioned that permissions must be lowered to `0600`, but from the STIG requirement [242459](https://www.stigviewer.com/stig/kubernetes/2021-04-14/finding/V-242459), it says:

```
The Kubernetes etcd must have file permissions set to 644 or more restrictive.
```

In this case, wouldn't the existing permission level `0644` suffice for the `.snap` files?

**Comment by JordanJordanov** [comment]
The more restrictive permissions were proposed by @vlerenc due to the sensitive information there. I also prefer to stick to `0600`

**Comment by vlerenc** [comment]
Indeed, https://www.stigviewer.com/stig/kubernetes/2021-04-14/finding/V-242459 (like the CIS Benchmark for Kubernetes, another often adopted industry standard) only requires `0644`, but since the rule already indicates "or more restrictive" and other areas like key files/credentials must be set to `0600`, it just seems prudent to protect also the ETCD files with these permissions, since they may/will contain such key files/credentials as well in their secrets. Then again, those are under API server ETCD encryption, so that is a weak argument. Was is left is that it contains critical data and unless it's a secret, it's not encrypted (and today end users cannot instruct us to include other resources for encryption, I believe).

So, on paper, only `0644` is required, but `0600` seems more prudent. This means, we don't have to implement `0600`, if that's not easy. I guess you ask, because we cannot easily influence the permissions? How is it done for the `.wal` files?
