### ISSUE TITLE
Parameter to limit maximum number of delta changes before a delta snapshot is triggered

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#81]
### Problem
The frequency of delta snapshots is only controlled by the parameter [`delta-snapshot-period-seconds`](https://github.com/gardener/etcd-backup-restore/blob/master/cmd/snapshot.go#L95).
In case of very frequent changes to ETCD, a large number of changes might be accumulated before the next delta snapshot is triggered according to the configured `delta-snapshot-period-seconds`.

Since, this is related to the load, the behaviour of the backup/restore sidecar could be unpredictable including a potential crash of the backup/restore sidecar if sufficient memory is not available to the sidecar container.

### Solution
To make things more robust, we must introduce a parameter (`max-changes-per-delta-snapshot`?) to limit the number of changes that are accumulated before a delta snapshot is triggered.

Delta snapshot could be triggered based on the new parameter (`max-changes-per-delta-snapshot`) or the older parameter (delta-snapshot-period-seconds`) whichever happens earlier.

### Alternative
Use maximum limit to the size of the delta change as a parameter. Could this be harder to compute than a simple number of changes?

**Comment by swapnilgm** [comment]
having limit on memory consumed rather than count of events make more sense to me. So, I have raised PR #84 for the same. You can have look at it. I found its not that hard to compute memory consumption with each event. Best solution I could found is to convert event into Json and get size of entire struct. I could actually traverse the struct and sum up only key value size but that would miss the memory due to other metadata.
