### ISSUE TITLE
Etcd liveness and readiness probe failed before Delta snapshot

### ISSUE THREAD

**Issue by nikhilsap** [gardener/etcd-backup-restore#92]
While doing load test on Etcd, we observed that , ETCD is going for restart after a work load and before the scheduled delta snapshot. 

In Pod details, it shows "Liveness Probe failed" and "Readiness Probe Failed" as shown below.

![image](https://user-images.githubusercontent.com/41104107/50825717-bb7f1700-135f-11e9-8905-7a7f33742db6.png)

Following is the pod status : 
![image](https://user-images.githubusercontent.com/41104107/50825801-f5501d80-135f-11e9-97bd-6f829fb342fb.png)

from the log, we didnt get any details of the restart. We are able to reproduce the same.

**Comment by swapnilgm** [comment]
#### Update to original issue statement :
After discussion with @nikhilsap, i got to know that,  the issue was observed only on etcd-backup-restore image with following patch post metrics api implementation PR #90 . i.e. When golang garbage collection trace is enabled and garbage collection value is set to 50%.

```
const defaultGCPercent = 50

func main() {
    if len(os.Getenv("GOMAXPROCS")) == 0 {
        runtime.GOMAXPROCS(runtime.NumCPU())
    }

    os.Setenv("GODEBUG", "gotrace=1")
  prev := debug.SetGCPercent(0)
  fmt.Println(prev)
  debug.SetGCPercent(defaultGCPercent)
  new := debug.SetGCPercent(defaultGCPercent)
  fmt.Println(new)

    stopCh := setupSignalHandler()
    command := cmd.NewBackupRestoreCommand(stopCh)
    if err := command.Execute(); err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
}
```

#### Action taken: 
I am not able to reproduce the issue on my side. Tried with different values of GC from 100-70-50-40%.

**Comment by swapnilgm** [comment]
@nikhilsap Will you please try to reproduce it with 0.5.1 image. If not i'll close the issue.

**Comment by nikhilsap** [comment]
@swapnilgm Image 0.5.1 works like charm. I didnt find this error anymore. 

So Closing it
