### ISSUE TITLE
Db is getting restored but not getting merged with original db.

### ISSUE THREAD

**Issue by PoojaGidaveer** [gardener/etcd-backup-restore#98]
Incase of ETCD, When the db is crashed, the restoration happens from previous backup but into different folder /var/etcd/data/new.etcd/member/snap instead of the main db folder- /var/etcd/data/member/snap.

Later we observed that this folder is not being merged into db folder. During the next backup cycle, it  is taken only  from /var/etcd/data/member/snap . So, the restored data  (/var/etcd/data/new.etcd) is not backed up in the next cycle.

**Comment by swapnilgm** [comment]
This is expected behaviour. If i'm correct you might be passing data-dir to etcd as `/var/etcd/data` and to etcd-backup-restore as `/var/etcd/data/new.etcd`. etcd-backup-restore asks snapshot from etcd which will eventually read from `/var/etcd/data` . While restoring etcd-backup-restore  will restore to data directory parameter passed to it i.e. `/var/etcd/data/new.etcd`. Please set the both values to same path.
